[package]
name = "flint-server"
description = "Flint data-plane node (v0: single-node RESP string server)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flint-resp = { path = "../flint-resp" }
flint-slot = { path = "../flint-slot" }
flint-storage = { path = "../flint-storage" }
flint-tls = { path = "../flint-tls" }

[lints]
workspace = true

[features]
rocks = ["flint-storage/rocksdb"]
